mystore/mystore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/store', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True, template_name="admin/login.html"), name="login"),
    path('', include(('store.urls', 'store'), namespace='app')),
    path('^admin/', admin.site.urls),
    path('doc/', include('django.contrib.admindocs.urls')),
    path('admin/password_reset/', auth_views.PasswordResetView.as_view(),name='admin_password_reset',),
    path('admin/password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done',),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm',),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete',),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mystore/store/urls.py
from django.urls import path
from store.views import Index, Panel, Report, Update, Return, Welcome, GetItem, ProcessTransaction
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
  path('', Index, name='index'),
  path('welcome/', login_required(Welcome), name='welcome'),
  path('panel/', login_required(Panel), name='panel'),
  path('item/', login_required(GetItem), name='item'),
  path('processTransaction/', login_required(ProcessTransaction), name='processTransaction'),
  path('report/', login_required(Report), name='report'),
  path('update/', login_required(Update.as_view()), name='update'),
  path('return/', login_required(Return.as_view()), name='return'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mystore/store/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
import uuid


def path(instance, filename):
  #create a unique path for item mugshot.
  return 'item_{0}/{1}'.format(instance.id, filename)
  


# Create your models here.

class User(AbstractUser): 
  
  """
  store a single user data.
  extend the django abstract-user class.
  and this model is the new auth_user_model
  """
  
  userType = (
      ('manager', 'manager'),
      ('supervisor', 'supervisor'),
      ('attendant', 'attendant'),
    )
  
  user_type = models.CharField(max_length=12, choices=userType, help_text="This field define the user access level to the store panel.")



class Item(models.Model):
  
   """
   store items information.
   """
    
   serial_no = models.CharField(max_length=20, unique=True, verbose_name='barcode')
   name = models.CharField(max_length=20)
   category = models.CharField(max_length=20)
   sub_catg = models.CharField(max_length=20, null=True, blank=True, verbose_name="sub-category")
   color = models.CharField(max_length=20, null=True, blank=True)
   size = models.CharField(max_length=20, null=True, blank=True)
   description = models.TextField(null=True, blank=True)
   quantity = models.IntegerField()
   cost_price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='cost price($)')
   selling_price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name='selling price($)')
   sold = models.IntegerField(null=True, blank=True)
   mugshot = models.ImageField(upload_to=path, null=True, blank=True)
   date = models.DateTimeField(auto_now=True)
   
   def __str__(self):
    "Returns the item tag name"
    tag = '%s (%s | %s)' % (self.name, self.category, self.sub_catg)
    return tag.title()
        
      
   
   
   
class Sale(models.Model):
  
  """
   store sales information.
  """
 
  serial_no = models.CharField(max_length=20, verbose_name='barcode')
  name = models.CharField(max_length=20)
  category = models.CharField(max_length=20)
  sub_catg = models.CharField(max_length=20, null=True, blank=True, verbose_name="sub-category")
  sold = models.IntegerField()
  total_profit = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="total profit($)")
  cost_price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="cost price($)")
  selling_price = models.DecimalField(max_digits=15, decimal_places=2, verbose_name="selling price($)")
  transaction = models.ForeignKey("Transaction", on_delete=models.SET_NULL, null=True, blank=True, related_name="sales")
  date_test = models.DateField(auto_now_add=True);
  
  
  def __str__(self):
    "Returns the sale tag"
    tag = '%s(sold: %s)' % (self.name, self.sold)
    return tag

  
      
 
   
class Transaction(models.Model):
  
  """
  store transactions information.
  A transaction technically involve a group of sales record.
  """
  attendant = models.CharField(max_length=20)
  date = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    "Returns the transaction tag"
    tag = '%s(date: %s)' % (self.attendant, self.date)
    return tag



class Returns(models.Model):
  """
  store item returns information.
  """
  
  item = models.ForeignKey("Item", on_delete=models.SET_NULL, null=True, blank=True, related_name="returns")
  quantity = models.IntegerField()
  date = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    "Returns the returns obj tag"
    tag = '%s(date: %s)' % (self.item.name, self.date)
    return tag

  
  
  
 
 

mystore/store/views.py
from django.shortcuts import render
from django.views import View
from django.core.exceptions import PermissionDenied
from .models import Item, Returns, Transaction, Sale
from django.http import JsonResponse
import json
from django.views.decorators.http import require_http_methods
import pandas as pd
from django.db import transaction
from django.db.models import Sum, CharField, FloatField
from django.utils import timezone
from django.db.models.functions import Cast






def Index(request):
  
   """
   return the store-app index page with a link to the login interface.
   """
  
   return render(request, 'index.html')







def Panel(request):
  
  """
  Check if user is logged in and then return the panel page. Every user can access this view.
  """
  
  return render(request, 'panel.html')
  







@require_http_methods(["POST",])
def GetItem(request):
  """
  return a json object of an item given it's serial_no
  """
  data = json.loads(request.body.decode('utf-8'))
  
  try:
    item = Item.objects.get(serial_no=data['serial_no'])
  except Item.DoesNotExist:
    return JsonResponse({'error': 'invalid serial number'}, status=400)
    
  available = item.quantity - item.sold
  if available <= 0:
    stock_info = "out of stock"
  else:
    stock_info = "in of stock"
  
  mugshot = ''
  if item.mugshot:
    mugshot = item.mugshot.url
    
  return JsonResponse({
    'success': stock_info,
    'item': {
      'id': item.serial_no,
      'available': available,
      'name': item.name,
      'category': item.category,
      'size': item.size,
      'price': item.selling_price,
      'mugshot': mugshot,
      'description': item.description,
    }
  })
  
  
  
  
  
  
  
  
@require_http_methods(["POST",])
def ProcessTransaction(request):
  """
  return a transaction_id after processing sales.
  """
  data = json.loads(request.body.decode('utf-8'))
  
  sales_arr = []
  item_arr = []
  
  for sold_item in data:
    try:
      item = Item.objects.get(serial_no=sold_item['id'])
    except Item.DoesNotExist:
      return JsonResponse({'error': 'invalid serial number'}, status=400)
      
    stock = item.quantity - item.sold
    if int(sold_item['quantity']) > stock:
      return JsonResponse({'error': 'item is out of stock'}, status=400)
    
    profit = (int(item.quantity) * float(item.selling_price)) - (int(item.quantity) * float(item.cost_price))
    
    sale = Sale(serial_no=item.serial_no, name=item.name, category=item.category, sub_catg=item.sub_catg, sold=sold_item['quantity'], cost_price=item.cost_price, selling_price=item.selling_price, total_profit=profit)
    
    item.sold += int(sold_item['quantity'])
    sales_arr.append(sale)
    item_arr.append(item)
    
  transact = Transaction.objects.create(attendant=request.user.username)
  
  for sales in sales_arr:
    sales.transaction = transact
    sales.save()
    
  for item in item_arr:
    item.save()
    
  return JsonResponse({
    'success': 'transaction successful',
    'transaction_id': transact.id
  })
  
  
      
  
    
  
  



def Report(request):
  
   """
   return the store-app report page, Only manager(supervisor) can access this view.
   """
   
   user_type = request.user.user_type
  
   if user_type == "manager":
      current_date = Sale.objects.latest('date_test').date_test

      # query sales data
      sales = Sale.objects.filter(date_test__gte=current_date - timezone.timedelta(weeks=16))
      sales = sales.order_by('-date_test')
      sales = sales.values('date_test').annotate(sold=Sum('sold'), aggr_profit=Sum('total_profit'))
      sales = sales.annotate(date_string=Cast('date_test', CharField()))
      sales = sales.annotate(profit=Cast('aggr_profit', FloatField()))
      
      # sold data
      sold = list(sales.values('date_string', 'sold'))
      
      # profit data
      profit = list(sales.values('date_string', 'profit'))
      
      salesObj = {
        'sold_data': sold,
        'profit_data': profit,
        'sale_summary': {
          'week_1': sale_summary(Sale.objects.filter(date_test__gte=current_date - timezone.timedelta(weeks=1))),
          'week_2': sale_summary(Sale.objects.filter(date_test__gte=current_date - timezone.timedelta(weeks=2))),
          'week_4': sale_summary(Sale.objects.filter(date_test__gte=current_date - timezone.timedelta(weeks=4))),
          'week_8': sale_summary(Sale.objects.filter(date_test__gte=current_date - timezone.timedelta(weeks=8))),
          'week_16': sale_summary(Sale.objects.filter(date_test__gte=current_date - timezone.timedelta(weeks=16))),
        }
      }
      
      return render(request, 'report.html', salesObj)
      
   raise PermissionDenied

 
  
def sale_summary(sales):
  return {
    'total_sales': sales.aggregate(Sum('sold'))['sold__sum'],
    'gross_profit': float(sales.aggregate(Sum('total_profit'))['total_profit__sum']),
    'most_sold_item': most_sold_dimension(sales.values('name').annotate(sold=Sum('sold')), 'name'),
    'most_sold_category': most_sold_dimension(sales.values('category').annotate(sold=Sum('sold')), 'category'),
    'most_sold_day': most_sold_dimension(sales.values('date_test').annotate(sold=Sum('sold')), 'date_test').strftime('%A'),
  };



def most_sold_dimension(sales, dimension):
  max_dimension = None
  most_sold = 0
  
  for sale in sales:
    if sale['sold'] > most_sold:
      most_sold = sale['sold']
      max_dimension = sale[dimension]
      
  return max_dimension
    
  
  
  




  
  
  
  
  
  
  
class Update(View):
  
  """
  This return the update page on get request and update the item-table in the store database on post request.
  Only supervisor and manager(superuser) can access this view.
  """
  
  template = 'update.html'
  
  def dispatch(self, request, *args, **kwargs):
    user_type = request.user.user_type
    if user_type == "manager" or user_type == "supervisor":
      return super().dispatch(request, *args, **kwargs)
    raise PermissionDenied
  
  def get(self, request, *args, **kwargs):
    return render(request, self.template)
    
    
  def post(self, request, *args, **kwargs):
    file = request.FILES['items_file']
    
    try:
        # Check if the file is a CSV or Excel file
        if file.name.endswith('.csv'):
            df = pd.read_csv(file)
        elif file.name.endswith(('.xls', '.xlsx')):
            df = pd.read_excel(file)
        else:
            return JsonResponse({'error': 'unsuppored file format'}, status=400)
    except Exception as e:
        return JsonResponse({'error': 'error reading file'}, status=400)
        
    items = df.iloc[0 : 8]
    index = 0
    
    try:
      with transaction.atomic():
         for index, row in items.iterrows():
            newItem= Item(serial_no=row["barcode"], name=row["name"], category=row["category"], color=row["color"], size=row["size"], description=row["description"], quantity=row["quantity"], cost_price=row["cost-price"], selling_price=row["selling-price"], sold=row["sold"])
            newItem.save()
    except Exception as e:
      #print(e)
      index += 1
      error = 'file-error: error on line %s' % index
      return JsonResponse({'error': error}, status=400)
      
    return JsonResponse({'success': 'items added to database'})
  
       
    







  
class Return(View):
  
  """
  This return the return page on get request and update the returns-table in the store database on post request.
  Only supervisor and manager(superuser) can access this view.
  """
  
  template = 'return.html'
  
  def dispatch(self, request, *args, **kwargs):
    user_type = request.user.user_type
    if user_type == "manager" or user_type == "supervisor":
      return super().dispatch(request, *args, **kwargs)
    raise PermissionDenied
  
  def get(self, request, *args, **kwargs):
    quantity = 0
    
    returned_items = Returns.objects.all()
    for item in returned_items:
      quantity += item.quantity
      
    return render(request, self.template, {'returns': quantity,})
    
    
  def post(self, request, *args, **kwargs):
    data = json.loads(request.body.decode('utf-8'))
    
    try:
      item = Item.objects.get(serial_no=data['item_id'])
    except Item.DoesNotExist:
      return JsonResponse({'error': 'invalid serial number'}, status=400)
      
    returns = Returns.objects.create(quantity=data['no_returned'])
    returns.item = item
    returns.save()
    return JsonResponse({'success': 'new return submitted successfully'})









def Welcome(request):
  
   """
   return the welcome page with a link to the store  panel.
   """
   template = "welcome.html"
   return render(request, template)

mystore/store/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
  
<style>

  @keyframes rotate {
    from {
      transform: rotateZ(0deg);
      width: 100px;
    }
    to {
      transform: rotateZ(360deg);
      width: 50px;
    }
  }
    
  body {
    background-color: #FFF5EE;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding-top: 200px;
  }
  
  img {
    width: 100px;
    border-radius: 30px;
    animation-name: rotate;
    animation-duration: 15s;
    animation-iteration-count: infinite;
    animation-direction: alternate;
  }
  
  a {
    position: absolute;
    text-decoration: none;
    font-weight: bold;
    font-size: 25px;
    bottom: 100px;
    color: #cc5500;
    text-align: center;
  }
  
</style>
</head>


<body>
  
  
<img src="{% static 'store/image/logo.jpg' %}" alt="site logo"/> 

<a href="{% url "login" %}">MY STORE</a>

<script>
   
</script>


</body>
</html>

mystore/store/templates/panel.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Store Panel Screen</title>
    
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/panel.css' %}">
   
   
   <style id="fullScreen">
    /* 
   this style is only enable on browser fullScreen mode.
   */
     header { 
       margin-top: 40px;
     }
     
     #logo {
       margin-top: 50px;
     }
     
   @media only screen and (max-width: 800px) { 
     #logo {
       margin-top: 40px;
     }
   }
     
   </style>
   
  </head>
  
<body>
  


  <main> 
    <header id="mainHead">
     <img id='pin' src="{% static 'store/image/pin.png' %}"/>
      <h4> {{ user.username }} </h4>
    </header>

 
  <a href="/admin/store"><img id="logo" src="{% static 'store/image/logo.jpg' %}"/></a>

  
  <div id="mainleft">
     <ul id="nav">
       <li><a id="active" href="{% url "app:panel" %}">Lookup</a></li>
       <li><a href="{% url "app:update" %}">Update</a></li>
       <li><a href="{% url "app:report" %}">Report</a></li>
       <li><a href="{% url "app:return" %}">Returns</a></li>
     </ul>
    
    <div id="utility">
      
    <h4> Look up product with </h4>
    
    <div id="loadItem">
    <img src="{% static 'store/image/barcode.jpg' %}" /> 
    </div>
    
    <p id="validate">barcode input is empty!!</p>
    <form>
      <input id="input" placeholder="Enter barcode" autofocus/>
      <span>
       <button id="look">
        <img src="{% static 'store/image/search.png' %}" /> 
       </button>
      </span>
    </form>
    
    <dl id="hint">
      <dt> <h4>Hint :</h4> </dt>
      <p>A physical USB-barcode-scanner is an alternative to keyboard for entering barcode prior to product look up.
      </p>
    </dl>
      
    </div>
    
  </div>
  </main>
  
  <div id="backdropA" class="backdrop" onclick="Close()"> </div>
  
  <section>
  <p id="itemCount"> 0 item added</p>
   <div id="sectionHeader">
    <p id="first"> PREVIEW 
      <span id="checkout">
       <button id="process">Process</button>
       <button id="cancel">Cancel</button>
      </span>
    </p>
    <ul id="preview">
      <li>Total goods: <span id="Tgoods"></span></li>
      <li>Total price($): <span id="Tprice"></span></li>
    </ul>
    <hr/>
    </div>
    
  
  
   <div id="contain">
    <!-- template for items added to transaction desk.
      <article>
        <span data-id="">X</span>
       <img data-id="" src="mystore~2.jpg" /> 
       <details>
         <summary>custardddddddddddddd</summary>
          <ul>
            <li>Price: $500</li>
            <li>Quantity: 30rrffrrrrrrrrrrrrrrrrrrrrr</li>
            <li>Size: 5ghhjjjjjkkjjjjjjjjjjjjjkkkkkkjj</li>
         </ul>
         </details>
      </article>
      -->
      </div>
  </section>
  
  
  <img class="drawer" id="stack" src="{% static 'store/image/stack.png' %}" />
  <img class="drawer" id="hide" src="{% static 'store/image/drawer.png' %}" /> 
  
  
  
  <!-- construct the dialog that show the item details on look up -->
  <dialog id="item">

  <form method="dialog">
    <button id="exit" value="cancel">X</button>
  </form>
   
  <img id="mugshot" alt="mugshot" /> 
  
  <div id="info">
  <p>Name: <span class="data" id="name">st-ives</span></p>
  <p>
    Available: <span class="data"><b id="available">20</b></span>
    </p>
  <p>
    Price($): <span class="data"><b id="price">$200</b></span>
  </p>
  <p>Quantity:
  <span><input id="quantity" type="number" value=1 autofocus></span>
  </p>
  <p>Size: <span class="data" id="size">none</span></p>
  <p>Category: <span class="data" id="category">beauty</span></p>
  
  <!-- hidden dialog contents-->
  <span class="hidden" id="description">description</span>
  <span class="hidden" id="id">ID</span>

  </div>
  
  <form method="dialog">
    <button id="add" value="add">Add item</button>
  </form>
  </dialog>
 
  
  
  <!-- construct the dialog that displays error on look up-->
  <dialog id="not_found">
  <p> Item not found ! </p>
  <form method="dialog">
  <p> <button value="cancel">cancel</button> </p>
  </form>
  </dialog>
  
  
 
<div id="backdropB" class="backdrop"> </div>

<!-- construct the dialog to preview and print receipt -->
<dialog id="receipt">
   <header>
    <h3>Transaction Successful!</h3>
   </header>
   
   <form method="dialog">
    <button id="print">Print Receipt</button>
   </form>

  <main>
   
   <h5>MY STORE</h5>
   <p id="store">
     <span>Address: 28 Adekunle Fajuyi Rd, Dugbe, Ibadan.</span>
     <br/>
     <span>Tel: 0905629927</span>
   </p>
   
   <p id="title">RECEIPT</p>
   
   <p id="receiptHead">
    <span>Description(qty)</span>
    <span class="floatR">Price</span>
   </p>
   
   
   <div id="table">
     <!-- receipt item templates.
     <p>
       <span> shhsiejehdbxbxhxusjjsnd</span>
       <span class="floatR"> &hsjssjsj</span>
     </p>
     -->
   </div>
   
   
  <p id="total">
    <span>Total</span>
    <span id="totalSpan" class="floatR">#1500</span>
  </p>

  <div id="barcode">
     <img/>
  </div>
  
  <p id="thanks">Thank You</p>
  
  </main>
</dialog>


<!-- construct the dialog that displays loader-->
<dialog id="spiner" autofocus>
<img src="{% static 'store/image/logo.jpg' %}" alt="site logo"/>
</dialog>
 
  
 
  
 <script src="{% static 'store/script/panelDom.js' %}"></script>
 <script src="{% static 'store/script/panelItem.js' %}"></script>
 <script src="{% static 'store/script/JsBarcode.all.min.js' %}" charset="UTF-8"></script>
 
</body>
</html>

mystore/store/templates/report.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Store Report Screen</title>
    
   <link rel="stylesheet" type="text/css" href="{% static 'store/css/report.css' %}">
    
  <style id="fullScreen">
   /* 
   this style is only enable on browser fullScreen mode.
   */
  
     header { 
       padding-top: 25px;
     }
     
     #chart {
       margin-top: 60px;
     }
     
     #nav {
       margin-top: 120px;
     }
     
     #right {
       margin-top: 60px;
     }
     
     #header > img {
       top: 40px;
     }
 </style>
 
  </head>
  
  
<body>

     
     <div id="header">
       <header>
       <b>SALE REPORT</b>
       </header>
       <div id="span">
         <span id="first" data-week="week_1"> 1 week </span>
         <span data-week="week_2"> 2 weeks </span>
         <span data-week="week_4"> 4 weeks</span>
         <span data-week="week_8"> 8 weeks </span>
         <span data-week="week_16"> 16 weeks </span>
       </div>
       <hr/>
     </div>
     
   
    
    <section id="left">  
    
    <img src="{% static 'store/image/logo.jpg' %}" alt="logo" />
    
    <ul id="nav">
       <li><a href="{% url "app:panel" %}">Lookup</a></li>
       <li><a href="{% url "app:update" %}">Update</a></li>
       <li><a id="active" href="{% url "app:report" %}">Report</a></li>
       <li><a href="{% url "app:return" %}">Returns</a></li>
     </ul>
    
    
     <div id="chart">
      <details open>
       <summary><b>Sale Chart</b>
       <span> a plot of items sold per day in the last 28 days</span>
       </summary>
      <div id="svg1" class="svg"> 
      <svg>
      </svg>
      </div>
      </details>
      
      <details>
       <summary><b>Profit Chart</b>
       <span> a plot of profit made per day in the last 28 days</span>
       </summary>
      <div id="svg2" class="svg"> 
      <svg>
      </svg>
      </div>
      </details>
      
     </div>
     </section>
     
     <section id="right"> 

     <div id="sales" class="growth summary">
       <h6>Total Sale</h6>
       <p>1200ffghhhhh0yyyuuuyy</p>
     </div>

     <div id="profit" class="growth summary">
       <h6>Gross Profit($) </h6>
       <p> $20000gghhhjjjjhhdhjdj</p>
     </div>
       
     <div id="item" class="summary">
       <h6>Most sold item</h6>
       <p>Cocac olagg ghhhbdjdjd</p>
     </div>

     <div id="category" class="summary">
       <h6>Most sold category</h6>
       <p>Beverageffg ghhhgdhdhdh</p>
     </div>

     <div id="day" class="summary">
       <h6>Day with most sold</h6>
       <p>Wednesdaygg ghhhdhdjdjd</p>
     </div>
     
     </section>
   
 
<script>
  let profitData = {{ profit_data|safe }};
  let soldData = {{ sold_data|safe }};
  let saleSummary = {{ sale_summary|safe }};
</script>

<script src="{% static 'store/script/report.js' %}"></script>     
<script src="{% static 'store/script/d3.min.js' %}"></script>
<script src="{% static 'store/script/chart.js' %}"></script>   


</body>
</html>

mystore/store/templates/return.html
{% load static %}
<!DOCTYPE html>
<html>
   <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Store Return Screen</title>
    <link rel="stylesheet" type="text/css" href="{% static 'store/css/return.css' %}">
    
  <style id="fullScreen">
    /* 
   this style is only enable on browser fullScreen mode.
    */
   body {
     padding-top: 40px;
   }
  </style>
 
  </head>
 
    
<body>
  
  <img src="{% static 'store/image/logo.jpg' %}"/>
  
  <div id="contain">
    
  <ul id="nav">
     <li><a href="{% url "app:panel" %}">Lookup</a></li>
     <li><a href="{% url "app:update" %}">Update</a></li>
     <li><a href="{% url "app:report" %}">Report</a></li>
     <li><a id="active" href="{% url "app:return" %}">Returns</a></li>
  </ul>
    
  <div id="upload">
    
   <details>
    <summary>Guide on populating returns record.</summary>
    <ul>
      <li>Input data will be use to update returns record.</li>
      <li>Receipt barcode is an optional field to validate customer's receipt.</li>
    </ul>
    </details>
    
    <section>
      <h4>ITEM RETURNS</h4>
      <p id="info"> </p>
      
      <article>
      <p id="sale">Total no of returned sales: <span>{{ returns }}</span></p>
      <input id="id" name="id" placeholder="Item barcode" autofocus/>
      <input id="code" name="code" placeholder="Receipt barcode" />
      <span>optional*</span>
      <br><br>
      no of return: <input id="return" value=1 type="number" name="return">
      <p><span>Note: </span>receipt barcode is optional.</p>
      </article>
     
     <p><button id="process">Process</button></p>
    </section>
    
    </div>
    </div>
    
  <!-- construct the dialog that displays success-->
  <dialog id="success" autofocus>
  <p>Process Successful !</p>
  <form method="dialog">
  <p> <button class="cancel">Okay</button> </p>
  </form>
  </dialog>
  
  
  <!-- construct the dialog that displays error-->
  <dialog id="not_found">
  <p> Failed, try again. </p>
  <form method="dialog">
  <p> <button class="cancel">cancel</button> </p>
  </form>
  </dialog>
 

 
  <!-- construct the dialog that displays loader-->
  <dialog id="spiner" autofocus>
  <img src="{% static 'store/image/logo.jpg' %}" alt="site logo"/>
  </dialog>


  <script src="{% static 'store/script/return.js' %}"></script>
  
</body>
</html>

mystore/store/templates/welcome.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>User welcome Page</title>
<style>

 html,body{
    margin: 0;
    background-color: #FFF5EE;
    user-select: none;
  }
  
 body > img {
    width: 40px;
    border-radius: 7px;
    position: absolute;
    top: 20px;
    left: 20px;
  }
  
  #welcome {
    margin-top: 200px;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  
  #welcome > img {
    width: 70px;
    transform: scale(2);
  }
  
  #welcome button {
    padding: 10px 30px 10px 30px;
    color: white;
    background-color: #E17E45;
    margin-top: 60px;
  }
  
  p.group {
    padding: 0;
    margin: 0;
    font-size: 15px;
    color: #0066b2;
  }
  

  
</style>
</head>
<body>
  
  <img src="{% static 'store/image/logo.jpg' %}" alt="logo" />
   
   <div id="welcome">
     <img src="{% static 'store/image/agent.png' %}" alt="logo" />
     <p>Welcome back <b>{{ user.username|capfirst }}</b></p>
     <p class="group">
       You are signed in as 
       {{ user.user_type|default:"unknown" }}
     </p>
     <a href="{% url "app:panel" %}"><button>Go to application</button></a>
   </div>


</body>
</html>